In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6])

print("Questao 1")
print("a) ", x[5])
print("b) ", x[1:4])
print("c) ", x[1:])
print("d) ", x[: -1])
print("e) ", x[5:1:-1])
print("f) ", x[[1,5,2,1,1]])

Questao 1
a)  6
b)  [2 3 4]
c)  [2 3 4 5 6]
d)  [1 2 3 4 5]
e)  [6 5 4 3]
f)  [2 6 3 2 2]


In [ ]:
M = np.array([[10, 2, 10, 5], [2, 5, 1, 6], [2, 4, 8, 10], [4, 10, 3, 5]])

print("Questao 2")
M[:,0] = 1
M[-1] = np.ones((1,4), dtype = int)
print(M)


Questao 2
[[ 1  2 10  5]
 [ 1  5  1  6]
 [ 1  4  8 10]
 [ 1  1  1  1]]


In [ ]:
A = np.array([1,2,3]).reshape((1,3))
B = np.array([3,2,1]).reshape((1,3))
M = np.array([[4,5,6],[6,5,3]])

print("Questao 3")
print("a) ", A + B)
print("b) ", A + M)
print("c) ", A.T)
print("d) ", A.T + B)
print("e) ", M - np.vstack([A,B]))
#print("f) ", np.vstack([A, B.T])) #dá erro pois o tamanho de colunas de B, quando transposta, não é o mesmo que o tamanho de colunas A
print("g) ", np.vstack([A, B]))
print("h) ", M - 3)
print("i)", A * B)
print("j)", np.matmul(A, B.T))


Questao 3
a)  [[4 4 4]]
b)  [[5 7 9]
 [7 7 6]]
c)  [[1]
 [2]
 [3]]
d)  [[4 3 2]
 [5 4 3]
 [6 5 4]]
e)  [[3 3 3]
 [3 3 2]]
g)  [[1 2 3]
 [3 2 1]]
h)  [[1 2 3]
 [3 2 0]]
i) [[3 4 3]]
j) [[10]]


In [ ]:
M = np.array([[2, 10, 7, 6], [3, 12, 25, 9]])

print("Questao 4")

M = np.append(M,[[30,21,19,1]], axis = 0)

print("a)", M)

B = np.delete(M, 0,1)

print("b)", B)

Questao 4
a) [[ 2 10  7  6]
 [ 3 12 25  9]
 [30 21 19  1]]
b) [[10  7  6]
 [12 25  9]
 [21 19  1]]


In [ ]:
import numpy as np

A = np.arange(31,75,2)
print("Questao 5")
print(A)

Questao 5
[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73]


In [ ]:
V = np.random.randint(100, size=10)

indice = np.argmax(V)
print(V[indice])
V[indice]= V [indice] ** 2
print(V[indice])


98
9604
